name: hotprot
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pandas
  - requests
  - numpy
  - scikit-learn
  - mlflow
  - optuna
  - matplotlib
  - pip:
      - torch==1.12.1
      - torchvision==0.13.1
      - torchaudio==0.12.1
      - pylab
      - pickle
      - fair-esm
      - fair-esm[esmfold]
      - dllogger @ git+https://github.com/NVIDIA/dllogger.git
      - openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307
