name: hotproto
channels:
  - pytorch
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit-dev
  - pandas
  - requests
  - numpy
  - scikit-learn
  - matplotlib
  - notebook
  - pip:
      - torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
      - wandb
      - dllogger@git+https://github.com/NVIDIA/dllogger.git
      - openfold@git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307
