program: hyperparameters.py
method: grid
name: overfit_on_train_set
metric:
  name: mse_loss
  goal: minimize
parameters:
  learning_rate:
    values: [0.3]
  model_hidden_layers:
    values: [2]
  model_first_hidden_units:
    values: [2048]
  epochs:
    values: [35]
  val_on_trainset:
    values: [true]
  dataset_limit:
    values: [16]
  optimizer: 
    values: ["sgd"]
  model: 
    values: ["cnn"]
  batch_size: 
    values: [2]