program: train.py
method: grid
name: esm2_avg_representations
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - --wandb
metric:
  name: mse_loss
  goal: minimize
parameters:
  learning_rate:
    values: [0.001,0.005, 0.01, 0.05, 0.1, 0.5]
  model_hidden_layers:
    values: [2,3,4]
  model_first_hidden_units:
    values: [1024, 512]
  epochs:
    values: [5]
  val_on_trainset:
    values: ["false"]
  optimizer: 
    values: ["sgd", "adam"]
  model: 
    values: ["fc"]
  batch_size: 
    values: [8,16]
  representation_key: 
    values: ["s_s_0_avg"]