program: applications/train.py
method: grid
name: esm2_repr_summarizer_fixed
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - --wandb
metric:
  name: mse_loss
  goal: minimize
parameters:
  learning_rate:
    values: [0.001]
  model_hidden_layers:
    values: [2]
  model_first_hidden_units:
    values: [1024]
  epochs:
    values: [10]
  val_on_trainset:
    values: ["false"]
  optimizer: 
    values: [ "adam"]
  model: 
    values: ["summarizer"]
  batch_size: 
    values: [32]
  representation_key: 
    values: ["s_s"]
  summarizer_type: 
    values: ["single_instance", "multi_instance"]
  summarizer_per_residue_out_size:
    values: [1, 8]
  summarizer_num_layers: 
    values: [1,2,3]
  model_dropoutrate:
    values: [0]
  summarizer_activation: 
    values: ["relu", "identity"]
  summarizer_mode:
    values: ["per_repr_position", "per_resiude"]